app/views/devise/passwords/new.html.erb
app/views/devise/sessions/new.html.erb

cambie el login y registration

front login y register

---

app/controllers/movies_controller.rb
app/views/devise/registrations/new.html.erb
app/views/movies/edit.html.erb
app/views/movies/index.html.erb
app/views/movies/new.html.erb
app/views/movies/show.html.erb
config/routes.rb
test/controllers/movies_controller_test.rb

movie controller

---

app/models/movie.rb

Validacion de Movie

---

app/models/rental.rb

se añade validaciones del rentals

---

app/controllers/movies_controller.rb
db/migrate/20230603210832_add_poster_to_movie.rb
db/schema.rb

Controller actions

---

app/models/rental.rb
app/views/movies/index.html.erb
config/routes.rb
db/seeds.rb

cambio de rutas y movies con seeds de rentals

---

app/views/movies/new.html.erb
app/views/movies/show.html.erb
app/views/rentals/edit.html.erb
app/views/rentals/index.html.erb
app/views/rentals/new.html.erb
config/routes.rb

cambios movies

---

app/assets/stylesheets/components/_card_category.scss
app/assets/stylesheets/components/_index.scss
app/views/movies/index.html.erb

Movies index

---

app/controllers/rentals_controller.rb
app/models/rental.rb
db/migrate/20230607003647_change_nameto_rental_date.rb
db/schema.rb

cambié en Rentals al nombre rent_date

Cambio de nombre de table

---

app/views/rentals/new.html.erb

merge con fecha new arreglada

---

app/views/movies/show.html.erb

Puse el boton "Alquilar" dentro de movies => show.html.erb (va al formulario con las fechas de rentall)

Boton alquilar 

---

app/controllers/movies_controller.rb

Ahora ya no pide logearse al querer ver las movies, solo lo pide cuando uno quiere rentar

Mover la autentificacion para la view rentals

---

app/views/users/show.html.erb
config/routes.rb
db/seeds.rb

ultimo push 8-6

---

app/views/movies/index.html.erb
app/views/movies/show.html.erb

se mejoro el frontend del index y show del movies

---

app/views/users/show.html.erb

cambios de show user

---

app/controllers/application_controller.rb
app/views/shared/_navbar.html.erb

Route del log in

---

app/assets/stylesheets/components/_banner.scss
app/views/movies/show.html.erb
app/views/shared/_navbar.html.erb

Front end Movies Show

---

app/views/movies/new.html.erb

Create a movie form

---

app/views/rentals/new.html.erb

cambie de orden botones back y create

---

app/views/shared/_navbar.html.erb

Boton del navbar que va a My rentals

My rentals path working

---

app/assets/stylesheets/components/_cards_movies.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_map.scss
app/views/movies/index.html.erb

apeliculas con mapa

---

app/views/movies/index.html.erb

peliculas new

---

app/views/movies/show.html.erb

Reverts TinkuMalibu/The-Real-Blockbuster#68

Revert "master new"

---

app/views/movies/index.html.erb

Reverts TinkuMalibu/The-Real-Blockbuster#67

Revert "peliculas new"

---

app/views/movies/index.html.erb
app/views/movies/show.html.erb

cambios show e index

---

app/views/users/my_movies.html.erb
app/views/users/show.html.erb

cambio en h1 rentals y published

rented and published

---

app/views/users/show.html.erb

cambio de orden de fecha my rentals

---

app/views/rentals/edit.html.erb
app/views/users/my_movies.html.erb
app/views/users/show.html.erb

My published movies

---

app/views/movies/show.html.erb

RENT THIS MOVIE CENTERED

---

app/models/movie.rb
app/views/users/show.html.erb
db/migrate/20230617164020_change_poster_url_to_movies.rb
db/schema.rb
db/seeds.rb

Rentalsdelete

---

app/views/movies/show.html.erb

Rent this movie btn

---

app/assets/stylesheets/components/_card_product.scss
app/views/rentals/new.html.erb

mas grande el create rent
